package model.AM.common;

import java.sql.ResultSet;

import java.sql.SQLException;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 07 12:30:11 EET 2016
// ---------------------------------------------------------------------
public interface LOGAM extends ApplicationModule {
    ResultSet CalculateValues(String mainId) throws SQLException;

    ResultSet getItemsByMainId(String mainId) throws SQLException;

    void ClearSearchMainItems();

    void SearchMainItems(String code, Date date, String chooseDate, Date startDate, Date endDate);

    void exeEmptyMainCtfItems();

    void resetMainCtf();

    void provideCtfMainByFacilityReport(String code);
}

