package model.View.client;

import model.View.common.CtfMainVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 04 13:16:00 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CtfMainVOClient extends ViewUsageImpl implements CtfMainVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CtfMainVOClient() {
    }

    public void applyProcessingDateSearch(String date) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "applyProcessingDateSearch", new String[] {
                                                                         "java.lang.String" }, new Object[] { date });
        return;
    }
}

