package model.View.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 04 13:15:59 EEST 2014
// ---------------------------------------------------------------------
public interface CtfMainVO extends ViewObject {
    void applyProcessingDateSearch(String date);
}

