package model.AM.client;

import java.sql.ResultSet;

import model.AM.common.LOGAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 07 12:30:11 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LOGAMClient extends ApplicationModuleImpl implements LOGAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LOGAMClient() {
    }


    public void SearchMainItems(String code, Date date) {
        Object _ret = this.riInvokeExportedMethod(this, "SearchMainItems", new String[] {
                                                  "java.lang.String", "oracle.jbo.domain.Date" }, new Object[] {
                                                  code, date });
        return;
    }


    public ResultSet CalculateValues(String mainId) {
        Object _ret = this.riInvokeExportedMethod(this, "CalculateValues", new String[] { "java.lang.String" }, new Object[] {
                                                  mainId });
        return (ResultSet) _ret;
    }

    public void ClearSearchMainItems() {
        Object _ret = this.riInvokeExportedMethod(this, "ClearSearchMainItems", null, null);
        return;
    }

    public void SearchMainItems(String code, Date date, String chooseDate, Date startDate, Date endDate) {
        Object _ret = this.riInvokeExportedMethod(this, "SearchMainItems", new String[] {
                                                  "java.lang.String", "oracle.jbo.domain.Date", "java.lang.String",
                                                  "oracle.jbo.domain.Date", "oracle.jbo.domain.Date"
        }, new Object[] { code, date, chooseDate, startDate, endDate });
        return;
    }

    public void exeEmptyMainCtfItems() {
        Object _ret = this.riInvokeExportedMethod(this, "exeEmptyMainCtfItems", null, null);
        return;
    }

    public ResultSet getItemsByMainId(String mainId) {
        Object _ret = this.riInvokeExportedMethod(this, "getItemsByMainId", new String[] { "java.lang.String" }, new Object[] {
                                                  mainId });
        return (ResultSet) _ret;
    }

    public void provideCtfMainByFacilityReport(String code) {
        Object _ret = this.riInvokeExportedMethod(this, "provideCtfMainByFacilityReport", new String[] {
                                                  "java.lang.String" }, new Object[] { code });
        return;
    }

    public void resetMainCtf() {
        Object _ret = this.riInvokeExportedMethod(this, "resetMainCtf", null, null);
        return;
    }
}

