package model.View;

import model.View.common.CtfMainVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 04 13:12:23 EEST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CtfMainVOImpl extends ViewObjectImpl implements CtfMainVO {
    /**
     * This is the default constructor (do not remove).
     */
    public void applyProcessingDateSearch(String date) {
        ensureVariableManager().setVariableValue("pD", date);
//          setpD(date);
//          setApplyViewCriteriaName("CtfMainVOCriteria");
//          executeQuery();
        this.executeQuery();
        }
    public CtfMainVOImpl() {
    }

    /**
     * Returns the variable value for pD.
     * @return variable value for pD
     */
    public String getpD() {
        return (String) ensureVariableManager().getVariableValue("pD");
    }

    /**
     * Sets <code>value</code> for variable pD.
     * @param value value to bind as pD
     */
    public void setpD(String value) {
        ensureVariableManager().setVariableValue("pD", value);
    }

    /**
     * Returns the variable value for pCode.
     * @return variable value for pCode
     */
    public String getpCode() {
        return (String) ensureVariableManager().getVariableValue("pCode");
    }

    /**
     * Sets <code>value</code> for variable pCode.
     * @param value value to bind as pCode
     */
    public void setpCode(String value) {
        ensureVariableManager().setVariableValue("pCode", value);
    }

    /**
     * Returns the variable value for startDate.
     * @return variable value for startDate
     */
    public String getstartDate() {
        return (String) ensureVariableManager().getVariableValue("startDate");
    }

    /**
     * Sets <code>value</code> for variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(String value) {
        ensureVariableManager().setVariableValue("startDate", value);
    }

    /**
     * Returns the variable value for endDate.
     * @return variable value for endDate
     */
    public String getendDate() {
        return (String) ensureVariableManager().getVariableValue("endDate");
    }

    /**
     * Sets <code>value</code> for variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(String value) {
        ensureVariableManager().setVariableValue("endDate", value);
    }

    /**
     * Returns the variable value for p_mainId.
     * @return variable value for p_mainId
     */
    public String getp_mainId() {
        return (String) ensureVariableManager().getVariableValue("p_mainId");
    }

    /**
     * Sets <code>value</code> for variable p_mainId.
     * @param value value to bind as p_mainId
     */
    public void setp_mainId(String value) {
        ensureVariableManager().setVariableValue("p_mainId", value);
    }

    /**
     * Returns the variable value for p_code.
     * @return variable value for p_code
     */
    public String getp_code() {
        return (String) ensureVariableManager().getVariableValue("p_code");
    }

    /**
     * Sets <code>value</code> for variable p_code.
     * @param value value to bind as p_code
     */
    public void setp_code(String value) {
        ensureVariableManager().setVariableValue("p_code", value);
    }
}

