package model.View;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 16:37:56 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CtfMainVORowImpl extends ViewRowImpl {
    public static final int ENTITY_CTFMAINEO = 0;
    public static final int ENTITY_FACILITYEO = 1;
    public static final int ENTITY_FACILITYEO1 = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CtfMainId {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfMainId();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FacilityId {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacilityId();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setFacilityId((Number) value);
            }
        }
        ,
        PDate {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getPDate();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setPDate((Date) value);
            }
        }
        ,
        DeDate {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getDeDate();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DeStaff {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getDeStaff();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LcDate {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getLcDate();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LcStaff {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getLcStaff();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfStatus {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfStatus();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setCtfStatus((String) value);
            }
        }
        ,
        CtfComments {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfComments();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setCtfComments((String) value);
            }
        }
        ,
        FacName {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacName();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setFacName((String) value);
            }
        }
        ,
        FacilityId1 {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacilityId1();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FacCode {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacCode();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setFacCode((String) value);
            }
        }
        ,
        FacTypeId {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacTypeId();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setFacTypeId((Number) value);
            }
        }
        ,
        SupCode {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getSupCode();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setSupCode((Number) value);
            }
        }
        ,
        FacName1 {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacName1();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setFacName1((String) value);
            }
        }
        ,
        FacilityId2 {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacilityId2();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItem {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItem();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainOverrete {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainOverrete();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainCondoms {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainCondoms();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainIuds {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainIuds();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainProvera {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainProvera();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainNorplant {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainNorplant();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CtfItemCtfMainLam {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getCtfItemCtfMainLam();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FacilityLOV {
            public Object get(CtfMainVORowImpl obj) {
                return obj.getFacilityLOV();
            }

            public void put(CtfMainVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(CtfMainVORowImpl object);

        public abstract void put(CtfMainVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CTFMAINID = AttributesEnum.CtfMainId.index();
    public static final int FACILITYID = AttributesEnum.FacilityId.index();
    public static final int PDATE = AttributesEnum.PDate.index();
    public static final int DEDATE = AttributesEnum.DeDate.index();
    public static final int DESTAFF = AttributesEnum.DeStaff.index();
    public static final int LCDATE = AttributesEnum.LcDate.index();
    public static final int LCSTAFF = AttributesEnum.LcStaff.index();
    public static final int CTFSTATUS = AttributesEnum.CtfStatus.index();
    public static final int CTFCOMMENTS = AttributesEnum.CtfComments.index();
    public static final int FACNAME = AttributesEnum.FacName.index();
    public static final int FACILITYID1 = AttributesEnum.FacilityId1.index();
    public static final int FACCODE = AttributesEnum.FacCode.index();
    public static final int FACTYPEID = AttributesEnum.FacTypeId.index();
    public static final int SUPCODE = AttributesEnum.SupCode.index();
    public static final int FACNAME1 = AttributesEnum.FacName1.index();
    public static final int FACILITYID2 = AttributesEnum.FacilityId2.index();
    public static final int CTFITEM = AttributesEnum.CtfItem.index();
    public static final int CTFITEMCTFMAINOVERRETE = AttributesEnum.CtfItemCtfMainOverrete.index();
    public static final int CTFITEMCTFMAINCONDOMS = AttributesEnum.CtfItemCtfMainCondoms.index();
    public static final int CTFITEMCTFMAINIUDS = AttributesEnum.CtfItemCtfMainIuds.index();
    public static final int CTFITEMCTFMAINPROVERA = AttributesEnum.CtfItemCtfMainProvera.index();
    public static final int CTFITEMCTFMAINNORPLANT = AttributesEnum.CtfItemCtfMainNorplant.index();
    public static final int CTFITEMCTFMAINLAM = AttributesEnum.CtfItemCtfMainLam.index();
    public static final int FACILITYLOV = AttributesEnum.FacilityLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CtfMainVORowImpl() {
    }

    /**
     * Gets CtfMainEO entity object.
     * @return the CtfMainEO
     */
    public EntityImpl getCtfMainEO() {
        return (EntityImpl) getEntity(ENTITY_CTFMAINEO);
    }

    /**
     * Gets FacilityEO entity object.
     * @return the FacilityEO
     */
    public EntityImpl getFacilityEO() {
        return (EntityImpl) getEntity(ENTITY_FACILITYEO);
    }

    /**
     * Gets FacilityEO1 entity object.
     * @return the FacilityEO1
     */
    public EntityImpl getFacilityEO1() {
        return (EntityImpl) getEntity(ENTITY_FACILITYEO1);
    }

    /**
     * Gets the attribute value for CTF_MAIN_ID using the alias name CtfMainId.
     * @return the CTF_MAIN_ID
     */
    public DBSequence getCtfMainId() {
        return (DBSequence) getAttributeInternal(CTFMAINID);
    }

    /**
     * Gets the attribute value for FACILITY_ID using the alias name FacilityId.
     * @return the FACILITY_ID
     */
    public Number getFacilityId() {
        return (Number) getAttributeInternal(FACILITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for FACILITY_ID using the alias name FacilityId.
     * @param value value to set the FACILITY_ID
     */
    public void setFacilityId(Number value) {
        setAttributeInternal(FACILITYID, value);
    }

    /**
     * Gets the attribute value for P_DATE using the alias name PDate.
     * @return the P_DATE
     */
    public Date getPDate() {
        return (Date) getAttributeInternal(PDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for P_DATE using the alias name PDate.
     * @param value value to set the P_DATE
     */
    public void setPDate(Date value) {
        setAttributeInternal(PDATE, value);
    }

    /**
     * Gets the attribute value for DE_DATE using the alias name DeDate.
     * @return the DE_DATE
     */
    public Date getDeDate() {
        return (Date) getAttributeInternal(DEDATE);
    }

    /**
     * Gets the attribute value for DE_STAFF using the alias name DeStaff.
     * @return the DE_STAFF
     */
    public String getDeStaff() {
        return (String) getAttributeInternal(DESTAFF);
    }

    /**
     * Gets the attribute value for LC_DATE using the alias name LcDate.
     * @return the LC_DATE
     */
    public Date getLcDate() {
        return (Date) getAttributeInternal(LCDATE);
    }

    /**
     * Gets the attribute value for LC_STAFF using the alias name LcStaff.
     * @return the LC_STAFF
     */
    public String getLcStaff() {
        return (String) getAttributeInternal(LCSTAFF);
    }

    /**
     * Gets the attribute value for CTF_STATUS using the alias name CtfStatus.
     * @return the CTF_STATUS
     */
    public String getCtfStatus() {
        return (String) getAttributeInternal(CTFSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CTF_STATUS using the alias name CtfStatus.
     * @param value value to set the CTF_STATUS
     */
    public void setCtfStatus(String value) {
        setAttributeInternal(CTFSTATUS, value);
    }

    /**
     * Gets the attribute value for CTF_COMMENTS using the alias name CtfComments.
     * @return the CTF_COMMENTS
     */
    public String getCtfComments() {
        return (String) getAttributeInternal(CTFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for CTF_COMMENTS using the alias name CtfComments.
     * @param value value to set the CTF_COMMENTS
     */
    public void setCtfComments(String value) {
        setAttributeInternal(CTFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for FAC_NAME using the alias name FacName.
     * @return the FAC_NAME
     */
    public String getFacName() {
        return (String) getAttributeInternal(FACNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FAC_NAME using the alias name FacName.
     * @param value value to set the FAC_NAME
     */
    public void setFacName(String value) {
        setAttributeInternal(FACNAME, value);
    }

    /**
     * Gets the attribute value for FACILITY_ID using the alias name FacilityId1.
     * @return the FACILITY_ID
     */
    public DBSequence getFacilityId1() {
        return (DBSequence) getAttributeInternal(FACILITYID1);
    }

    /**
     * Gets the attribute value for FAC_CODE using the alias name FacCode.
     * @return the FAC_CODE
     */
    public String getFacCode() {
        return (String) getAttributeInternal(FACCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FAC_CODE using the alias name FacCode.
     * @param value value to set the FAC_CODE
     */
    public void setFacCode(String value) {
        setAttributeInternal(FACCODE, value);
    }

    /**
     * Gets the attribute value for FAC_TYPE_ID using the alias name FacTypeId.
     * @return the FAC_TYPE_ID
     */
    public Number getFacTypeId() {
        return (Number) getAttributeInternal(FACTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for FAC_TYPE_ID using the alias name FacTypeId.
     * @param value value to set the FAC_TYPE_ID
     */
    public void setFacTypeId(Number value) {
        setAttributeInternal(FACTYPEID, value);
    }

    /**
     * Gets the attribute value for SUP_CODE using the alias name SupCode.
     * @return the SUP_CODE
     */
    public Number getSupCode() {
        return (Number) getAttributeInternal(SUPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUP_CODE using the alias name SupCode.
     * @param value value to set the SUP_CODE
     */
    public void setSupCode(Number value) {
        setAttributeInternal(SUPCODE, value);
    }

    /**
     * Gets the attribute value for FAC_NAME using the alias name FacName1.
     * @return the FAC_NAME
     */
    public String getFacName1() {
        return (String) getAttributeInternal(FACNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for FAC_NAME using the alias name FacName1.
     * @param value value to set the FAC_NAME
     */
    public void setFacName1(String value) {
        setAttributeInternal(FACNAME1, value);
    }

    /**
     * Gets the attribute value for FACILITY_ID using the alias name FacilityId2.
     * @return the FACILITY_ID
     */
    public DBSequence getFacilityId2() {
        return (DBSequence) getAttributeInternal(FACILITYID2);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItem.
     */
    public RowIterator getCtfItem() {
        return (RowIterator) getAttributeInternal(CTFITEM);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainOverrete.
     */
    public RowIterator getCtfItemCtfMainOverrete() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINOVERRETE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainCondoms.
     */
    public RowIterator getCtfItemCtfMainCondoms() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINCONDOMS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainIuds.
     */
    public RowIterator getCtfItemCtfMainIuds() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINIUDS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainProvera.
     */
    public RowIterator getCtfItemCtfMainProvera() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINPROVERA);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainNorplant.
     */
    public RowIterator getCtfItemCtfMainNorplant() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINNORPLANT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CtfItemCtfMainLam.
     */
    public RowIterator getCtfItemCtfMainLam() {
        return (RowIterator) getAttributeInternal(CTFITEMCTFMAINLAM);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FacilityLOV.
     */
    public RowSet getFacilityLOV() {
        return (RowSet) getAttributeInternal(FACILITYLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

